spring.application.name=task-service

# ????????? Spring, ??? ?? ?????????? ??????? SQLite
spring.jpa.database-platform=org.hibernate.dialect.SQLiteDialect

# ??????????? ? ????
spring.datasource.url=jdbc:sqlite:myProject/task-service/app.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# ????????? ?????????????? ???????? ??????
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# ???????? Flyway
spring.flyway.enabled=true