spring.application.name=task-service

# ??????????? ? ?????????? ????? SQLite (???? tasks.db ????????? ???)
spring.datasource.url=jdbc:sqlite:tasks.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# ????????? Spring, ??? ?? ?????????? ??????? SQLite
spring.jpa.database-platform=org.hibernate.dialect.SQLiteDialect

# ?????????????? ???????? ?????? ?? ?????? ????? Java-??????? (@Entity)
spring.jpa.hibernate.ddl-auto=update

# ?????????? SQL-??????? ? ??????? (????? ???????? ??? ???????)
spring.jpa.show-sql=true
